### PR TITLE
Fragment Shader Support

### PR DESCRIPTION
**Pull request by thegtproject**

### CODE REVIEW

**Comment by peterhellberg** [comment]
I've tried this out and it seem to work well. (macOS High Sierra 10.13.6)

**Comment by thegtproject** [comment]
Couple of examples based on one of your experiments: https://github.com/thegtproject/pixelshaderexamples

________________________________

**Comment by peterhellberg** [comment]
@thegtproject Yes, those examples are what I tried out 👍

**Comment by thegtproject** [comment]
Reopening with the recreated fork

**Pull request closed without merging**
